### ISSUE TITLE
Deploy.sh does not pick the KUBERNETES_MASTER 

### ISSUE THREAD

**Issue by kasunbg** [dewmini/TestGrid-APIM-resources#3]
I run deploy.sh by providing the KUBERNETES_MASTER as an input. Same master is configured in k8s.properties as well.

But, for some reason, it fails to start-up with the below error:

```
bash deploy.sh http://192.168.89.70:8080                                                          
kubectl doesn't seem to work. Are Kubernetes Master details correctly configured?
```

The direct kubectl commands did not work as well. In the end, it turned out kubectl reads the `~/.kube/config` file to find the master.

```yaml
11:58:15 › cat ~/.kube/config 
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: http://192.168.89.70:8080
  name: scratch
contexts:
- context:
    cluster: scratch
    namespace: wso2
    user: experimenter
  name: exp-scratch
current-context: exp-scratch
kind: Config
preferences: {}
users:
- name: experimenter
  user:
    as-user-extra: {}
    password: exp
    username: exp
```

It is not correct to depend on a global config file like this IMO.
